sudo: true
language: c++
compiler:
    - gcc

before_script:
      # C++17
    - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
    - sudo apt-get update -qq
    - sudo apt-get install -qq g++-7
    - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-7 90
    - sudo apt-get install -y pkg-config python libboost-python-dev python-pip
    - sudo wget https://github.com/downloads/0vercl0k/rp/rp-lin-x64 -O /usr/local/bin/rp++
    - sudo pip2 install pwntools unicorn

script:
    - cd /tmp/
    - sudo git clone https://github.com/kriw/radare2
    - cd /tmp/radare2
    - sudo ./configure > /dev/null
    - sudo make -j2 > /dev/null
    - sudo make install > /dev/null
    - cd /tmp/
    - git clone https://github.com/kriw/ropchain
    - cd /tmp/ropchain
    - sudo python2 setup.py install
    - cd /tmp/ropchain/ropchain
    - travis_wait 30 python2 test.py -v
    - sudo rm -rf /tmp/ropchain
